[project]
name = "blender-mcp-slim"
version = "1.5.5"
description = "Blender MCP slim: a dependency-free Model Context Protocol server for LLMs"
readme = "README.md"
requires-python = ">=3.10"
authors = [{name = "5t3w3"}]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
blender-mcp-slim = "blender_mcp.server:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[project.urls]
"Homepage" = "https://github.com/5t3w3/blender-mcp-slim"
"Bug Tracker" = "https://github.com/5t3w3/blender-mcp-slim/issues"
"Original Project" = "https://github.com/ahujasid/blender-mcp"
